name: Selenium Test Suite
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ manin ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JKDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run tests
        run: mvn test -Dbrowser=chrome

      - name: Upload Extent Report
        if: always()
        uses: actions/upload-artificat@v4
        with:
          name: extent-report
          path: test-output/*.html
